"""add paymenth_method

Revision ID: 85d8b5e0f9a2
Revises: 92c3d66f7300
Create Date: 2024-10-02 12:20:53.087930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85d8b5e0f9a2'
down_revision = '92c3d66f7300'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type
    payment_method_enum = postgresql.ENUM('Card', 'Paypal', 'Klarna', name='payment_method')
    payment_method_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Enum('Card', 'Paypal', 'Klarna', name='payment_method')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
            
    # Drop the enum type
    payment_method_enum = postgresql.ENUM('Card', 'Paypal', 'Klarna', name='payment_method')
    payment_method_enum.drop(op.get_bind())

    # ### end Alembic commands ###
