"""Add SellersOrders table

Revision ID: 92c3d66f7300
Revises: 5d863ea43fbe
Create Date: 2024-09-28 19:34:37.330491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c3d66f7300'
down_revision = '5d863ea43fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_order_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Enum('Pending', 'Shipped', 'Delivered', name='order_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total')

    op.drop_table('sellers_orders')
    # ### end Alembic commands ###
