"""Make shipping_address and payment_method non-null in orders table

Revision ID: 9cb6e8d003f6
Revises: 4778122fda97
Create Date: 2025-01-16 17:43:03.965912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cb6e8d003f6'
down_revision = '4778122fda97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('Card', 'Paypal', 'Klarna', name='payment_method'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('Card', 'Paypal', 'Klarna', name='payment_method'),
               nullable=True)
        batch_op.alter_column('shipping_address',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
